# Generated by Django 3.1.7 on 2021-07-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='lyrics',
        ),
        migrations.AlterField(
            model_name='blog',
            name='composer',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='blog',
            name='genre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='rel_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='singer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
